import PrimeVue from 'primevue/config';
import Aura from '@primeuix/themes/aura';
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';
import type { App } from 'vue';

export function setupPrimeVue(app: App) {
  app.use(PrimeVue, {
    theme: {
      preset: Aura,
      options: {
        darkModeSelector: '.p-dark',
        cssLayer: {
          name: 'primevue',
          order: 'tailwind-base, primevue, tailwind-utilities'
        }
      }
    },
    locale: {
      startsWith: 'Dimulai dengan',
      contains: 'Mengandung',
      notContains: 'Tidak mengandung',
      endsWith: 'Berakhir dengan',
      equals: 'Sama dengan',
      notEquals: 'Tidak sama dengan',
      noFilter: 'Tanpa Filter',
      lt: 'Kurang dari',
      lte: 'Kurang dari sama dengan',
      gt: 'Lebih dari',
      gte: 'Lebih dari sama dengan',
      dateIs: 'Tanggal adalah',
      dateIsNot: 'Tanggal bukan',
      dateBefore: 'Tanggal sebelum',
      dateAfter: 'Tanggal sesudah',
      clear: 'Bersihkan',
      apply: 'Terapkan',
      matchAll: 'Cocokkan Semua',
      matchAny: 'Cocokkan Salah Satu',
      addRule: 'Tambah Aturan',
      removeRule: 'Hapus Aturan',
      accept: 'Ya',
      reject: 'Tidak',
      choose: 'Pilih',
      upload: 'Unggah',
      cancel: 'Batal',
      dayNames: ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'],
      dayNamesShort: ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'],
      dayNamesMin: ['Mi','Se','Sl','Ra','Ka','Ju','Sa'],
      monthNames: ['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'],
      monthNamesShort: ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun','Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'],
      chooseYear: 'Pilih Tahun',
      chooseMonth: 'Pilih Bulan',
      chooseDate: 'Pilih Tanggal',
      prevDecade: 'Dekade Sebelumnya',
      nextDecade: 'Dekade Berikutnya',
      prevYear: 'Tahun Sebelumnya',
      nextYear: 'Tahun Berikutnya',
      prevMonth: 'Bulan Sebelumnya',
      nextMonth: 'Bulan Berikutnya',
      prevHour: 'Jam Sebelumnya',
      nextHour: 'Jam Berikutnya',
      prevMinute: 'Menit Sebelumnya',
      nextMinute: 'Menit Berikutnya',
      prevSecond: 'Detik Sebelumnya',
      nextSecond: 'Detik Berikutnya',
      am: 'AM',
      pm: 'PM',
      today: 'Hari ini',
      weekHeader: 'Wk',
      firstDayOfWeek: 1,
      dateFormat: 'dd/mm/yy',
      weak: 'Lemah',
      medium: 'Sedang',
      strong: 'Kuat',
      passwordPrompt: 'Masukkan kata sandi',
      emptyFilterMessage: 'Tidak ada opsi yang ditemukan',
      searchMessage: '{0} hasil tersedia',
      selectionMessage: '{0} item terpilih',
      emptySelectionMessage: 'Tidak ada item terpilih',
      emptySearchMessage: 'Tidak ada hasil yang ditemukan',
      emptyMessage: 'Tidak ada opsi yang tersedia',
      aria: {
        trueLabel: 'Benar',
        falseLabel: 'Salah',
        nullLabel: 'Tidak dipilih',
        star: 'Bintang 1',
        stars: 'Bintang {star}',
        selectAll: 'Pilih Semua',
        unselectAll: 'Batal Pilih Semua',
        close: 'Tutup',
        previous: 'Sebelumnya',
        next: 'Berikutnya',
        navigation: 'Navigasi',
        scrollTop: 'Gulir ke Atas',
        moveTop: 'Pindah ke Atas',
        moveUp: 'Pindah ke Atas',
        moveDown: 'Pindah ke Bawah',
        moveBottom: 'Pindah ke Bawah',
        moveToTarget: 'Pindah ke Target',
        moveToSource: 'Pindah ke Sumber',
        moveAllToTarget: 'Pindah Semua ke Target',
        moveAllToSource: 'Pindah Semua ke Sumber',
        pageLabel: 'Halaman {page}',
        firstPageLabel: 'Halaman Pertama',
        lastPageLabel: 'Halaman Terakhir',
        nextPageLabel: 'Halaman Berikutnya',
        prevPageLabel: 'Halaman Sebelumnya',
        rowsPerPageLabel: 'Baris per halaman',
        jumpToPageDropdownLabel: 'Lompat ke Hal Dropdown',
        jumpToPageInputLabel: 'Lompat ke Hal Input',
        selectRow: 'Pilih Baris',
        unselectRow: 'Batal Pilih Baris',
        expandRow: 'Lebarkan Baris',
        collapseRow: 'Lipat Baris',
        showFilterMenu: 'Tampilkan Menu Filter',
        hideFilterMenu: 'Sembunyikan Menu Filter',
        filterOperator: 'Operator Filter',
        filterConstraint: 'Konstanta Filter',
        editRow: 'Edit Baris',
        saveEdit: 'Simpan Edit',
        cancelEdit: 'Batal Edit',
        listView: 'Tampilan Daftar',
        gridView: 'Tampilan Grid',
        slide: 'Geser',
        slideNumber: 'Geser {slideNumber}',
        zoomImage: 'Perbesar Gambar',
        zoomIn: 'Perbesar',
        zoomOut: 'Perkecil',
        rotateRight: 'Putar Kanan',
        rotateLeft: 'Putar Kiri'
      }
    }
  });

  app.use(ConfirmationService);
  app.use(ToastService);
}
